---
# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json
name: image

"on":
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: Install tools
        uses: jdx/mise-action@v4

      - name: Install deps
        run: npm ci

      - name: Build theme
        run: npm run build-keycloak

      - name: Ghcr login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute version
        id: version
        run: |
          if [ "${GITHUB_REF_TYPE}" = "tag" ]; then
            echo "value=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
          else
            echo "value=latest" >> "$GITHUB_OUTPUT"
          fi

      - name: Push artifact
        run: |
          TMP="$(mktemp -d)"

          LAYER_TAR="${TMP}/layer.tar"
          LAYER_TAR_GZ="${LAYER_TAR}.gz"
          CONFIG_JSON="${TMP}/config.json"

          cp dist_keycloak/keycloak-theme-for-kc-26.2-and-above.jar "${TMP}/keycloak-theme.jar"
          tar -cf "${LAYER_TAR}" -C "${TMP}" keycloak-theme.jar

          DIFF_ID="sha256:$(shasum -a 256 "${LAYER_TAR}" | cut -d' ' -f1)"
          echo "  diff_id: ${DIFF_ID}"

          gzip -9 -c "${LAYER_TAR}" >"${LAYER_TAR_GZ}"

          cat >"${CONFIG_JSON}" <<EOF
          {
            "architecture": "amd64",
            "os": "linux",
            "rootfs": {
              "type": "layers",
              "diff_ids": ["${DIFF_ID}"]
            }
          }
          EOF

          ORAS=$(mise which oras || which oras)
          cd "${TMP}"

          "${ORAS}" push ghcr.io/cloudpunks/keycloak-theme:${{ steps.version.outputs.value }} \
            --annotation "org.opencontainers.image.title=Theme" \
            --annotation "org.opencontainers.image.description=Custom theme for Keycloak" \
            --annotation "org.opencontainers.image.vendor=cloudpunks GmbH <ops@cloudpunks.de>" \
            --annotation "org.opencontainers.image.licenses=Apache-2.0" \
            --annotation "org.opencontainers.image.url=${{ github.server_url }}/${{ github.repository }}" \
            --annotation "org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}" \
            --annotation "org.opencontainers.image.revision=${{ github.sha }}" \
            --annotation "org.opencontainers.image.created=$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
            --config "$(basename ${CONFIG_JSON}):application/vnd.oci.image.config.v1+json" \
            "$(basename ${LAYER_TAR_GZ}):application/vnd.oci.image.layer.v1.tar+gzip"

...
